global:
  image: 
    repoitory: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/dev
    tag: "3.3.8"

controller:
  image:
    repository: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/dev
    tag: "3.3.8"

repoServer:
  image:
    repository: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/dev
    tag: "3.3.8"

server:
  image:
    repository: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/dev
    tag: "3.3.8"

dex:
  image:
    repository: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/dev
    tag: "3.3.8"

notifications:
  image:
    repository: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/argocd-notifications-controller
    tag: "3.3.8"

redis:
  image:
    repository: 314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/redis
    tag: "7.0

server:
  service:
    type: LoadBalancer

  ingress:
    enabled: false   # keep simple for now (no ingress yet)

configs:
  params:
    server.insecure: true

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

redis:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi