name: APP CI
on:
    push:
        branches: [abz]
    pull_request:
jobs:
    build-scan-push:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        env:
            AWS_REGION: us-east-1
            ECR-REPO: app-repo
        steps:
            - name: Check ECR exists
              run: |
                 aws ecr describe-repositories --repository-names $ECR_REPO
            - name: checkout
              uses: actions/checkout@v4
            - name: configure AWS creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::314133462348:role/github-actions-prod
                aws-region: ${{ env.AWS_REGION}}
            - name: login to ECR
              uses: aws-actions/amazon-ecr-login@v2
            - name: set image tag
              id: vars
              run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
            - name: build image
              run: |
                docker build -t $ECR_REPO:$IMAGE_TAG .
            - name: scan image
              uses: aquasecurity/trivy-action@v0.24.0
              with:
                image-ref: ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
                severity: CRITICAL
                exit-code: 1
            - name: tag image to ECR
              run: |   
                ACCOUNT_ID: $(aws sts get-caller-identity --query Account --output text)
                docker tag $ECR_REPO:$IMAGE_TAG \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

            - name: push to ECR
              run: |
                ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                docker push \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG