name: Terraform CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - abz

jobs:
  plan:
    environment: dev
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314133462348:role/github-actions-prod
          aws-region: us-east-1
          role-duration-seconds: 3600

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Init
        run: terraform init

      - name: Plan
        run: terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: dev   # 👈 IMPORTANT

    permissions:
      id-token: write
      contents: read
    env:
      CLUSTER_NAME: "example"
      AWS_REGION: "us-east-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314133462348:role/github-actions-prod
          aws-region: us-east-1
          role-duration-seconds: 3600

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve tfplan
      - name: Upload errored state (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: errored-tfstate
          path: errored.tfstate
      - name: Login to ECR
        run: |
           aws ecr get-login-password --region $AWS_REGION | \
           docker login --username AWS --password-stdin 314133462348.dkr.ecr.us-east-1.amazonaws.com    
      - name: Pull & Push Argocd images to ECr
        run: |
            ECR=314133462348.dkr.ecr.us-east-1.amazonaws.com/worldclassprodgrade/dev
            docker pull quay.io/argoproj/argocd:v3.3.8
            docker tag quay.io/argoproj/argocd:v3.3.8 $ECR:argocd-v3.3.8
            docker push $ECR:argocd-v3.3.8
            docker tag quay.io/argoproj/argocd:v3.3.8 $ECR:argocd-repo-server-3.3.8
            docker push $ECR:argocd-repo-server-3.3.8
            docker tag quay.io/argoproj/argocd:v3.3.8 $ECR:argocd-application-controller-3.3.8
            docker push $ECR:argocd-application-controller-3.3.8
            docker tag quay.io/argoproj/argocd:v3.3.8 $ECR:argocd-dex-server-3.3.8
            docker push $ECR:argocd-dex-server-3.3.8
            docker pull redis:7.0
            docker tag quay.io/argoproj/argocd:v3.3.8 $ECR:argocd-notifications-controller-3.3.8
            docker push $ECR:argocd-notifications-controller-3.3.8
            docker pull redis:7.0
            docker tag redis:7.0 $ECR:redis-7.0
            docker push $ECR:redis-7.0
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
      - name: wait for node
        run: |
          kubectl get nodes
          echo "Waiting for nodes to become Ready..."
          kubectl wait --for=condition=Ready nodes --all --timeout=300s
      
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd || true
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            -f helm-charts/values/argocd-values.yaml \
            --wait \
            --timeout 10m
      

      - name: Upload errored state (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
              name: errored-tfstate
              path: errored.tfstate